[pyprland]
plugins = [
  "expose",
  "scratchpads",
  "workspaces_follow_focus",
  "lost_windows",
  "toggle_special",
#  "monitors",
#  "fetch_client_menu",
#  "magnify",
#  "shift_monitors",
#  "menubar",
]

[scratchpads.term]
animation = "fromTop"
command = "alacritty"
class = "Alacritty"
size = "96% 96%"
position = "2% 2%"
# max_size = "1920px 100%"
lazy = true

[scratchpads.calc]
animation = "fromTop"
command = "qalculate-gtk"
class = "qalculate-gtk"
size = "50% 50%"
position = "25% 25%"
# max_size = "1920px 100%"
lazy = true

[scratchpads.volume]
animation = "fromTop"
command = "pavucontrol -t 3"
class = "org.pulseaudio.pavucontrol"
size = "60% 60%"
position = "20% 20%"
unfocus = "hide"
lazy = true

[scratchpads.blueman]
animation = "fromTop"
command = "blueman-manager"
class = "blueman-manager"
size = "60% 60%"
# position = "20% 20%"
unfocus = "hide"
lazy = true

[workspaces_follow_focus]
max_workspaces = 10

# [monitors.placement."eDP-1"]
# leftCenterOf = "HDMI-A-1"
# rate = 144
# scale = 1
# transform = 0
# resolution = "1920x1080"
#
# [monitors.placement."HDMI-A-1"]
# rightCenterOf = "eDP-1"
# rate = 60
# scale = 1
# transform = 0
# resolution = "2560x1440"

# [layout_center]
# margin = 60
# offset = [0, 30]
# next = "movefocus r"
# prev = "movefocus l"
# next2 = "movefocus d"
# prev2 = "movefocus u"
