add_newline = false

format = """\
$username$directory\
[](fg:color4 bg:color5)\
$git_branch\
$git_status\
[](fg:color5 bg:color6)\
$python\
[](fg:color6)\
$character\
"""

palette = 'colors'

[palettes.colors]
color1 = '#24273a'
color2 = '#ffffff'
color3 = '#c6a0f6'
color4 = '#7dc4e4'
color5 = '#ee99a0'
color6 = '#a6da95'
color7 = '#8bd5ca'
color8 = '#eed49f'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
format = '[ 󱑍 $time ](fg:color1 bg:color3)'

[cmd_duration]
min_time = 3000
format = "[󱑎 $duration ](fg:color1 bg:color3)"

[username]
format = '[ $user](fg:color1 bg:color4)'

[directory]
format = "[ $path ](fg:color1 bg:color4)"

[git_branch]
format = '[ $symbol$branch(:$remote_branch) ](fg:color1 bg:color5)'
symbol = "  "

[git_status]
format = '[$all_status ](fg:color1 bg:color5)'

[git_metrics]
format = "([+$added ]($added_style))[]($added_style)"
added_style = "fg:color1 bg:color5"
deleted_style = "fg:color1 bg:color5"
disabled = false

[hg_branch]
format = "[ $symbol$branch ]"
symbol = " "

[python]
# Show python version and virtual environment name
python_binary = ["python3", "python"]
format = "[ (${virtualenv}) ](fg:color1 bg:color6)"

[character]
success_symbol = '[](color1 bold)'
error_symbol = '[ ✗](#ffb4ab bold)'
